### ISSUE TITLE
USER STORY: View Reviews

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#1]
As a **Site User** I can **view reviews from previous buyers** so that **I know how good the site's purchasing experience is handled**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must be able to find them easily within the home page. 

**Tasks**
- [x] Create a section within index.html where reviews and their data can be displayed.
- [x] Create a reviews app and add a custom review model to include (feedback, rating, date, by who).
- [x] Set up the urls.py and add review model as context to index.html.
- [x] Add control of creating reviews via admin panel by creating admin.py.
