### ISSUE TITLE
USER STORY: Account Sign In

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#10]
As a **Site User** I can **sign in to my website account** so that **I can interact with the club's website and its features**

**Acceptance Criteria:**
- Acceptance Criteria 1: Use Django AllAuth to allow users to Sign In when returning to the website.
- Acceptance Criteria 2: Use Username and Password to sign in.
- Acceptance Criteria 3: Include link to sign in via header.

**Tasks**
- [x] Style and customise login.html to include username and password fields.
- [x] Add url link to my account in main header of base.html.
- [x] Add url link to my account in mobile top header.
