### ISSUE TITLE
USER STORY: Account Sign Out

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#11]
As a **Site User** I can **sign out of my account** so that **I know my account is safe**

**Acceptance Criteria:**
- Acceptance Criteria 1: Link to logout.html must be available within my account section in header.
- Acceptance Criteria 2: Site User is asked to make sure they wish to sign out.
- Acceptance Criteria 3: Use Django AllAuth to allow users to Sign Out when returning to the website.

**Tasks**
- [x] Link logout.html within my account section of main header.
- [x] Style and customise logout.html to match overall theme of website.
- [x] Create a defensive user question with "Yes" to confirm signing out and "No" to cancel signing out.
