### ISSUE TITLE
USER STORY: Create Profile

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#15]
As a **Site User** I can **create a profile** so that **I do not have to retype the same details when making several purchases**

**Acceptance Criteria:**
- Acceptance Criteria 1: Have an application which holds all user profile details.
- Acceptance Criteria 2: Once logged in, users can update their profile.
- Acceptance Criteria 3: Profile to include billing details fields and excluding email field which is directly linked with AllAuth. 
- Acceptance Criteria 4: All fields must be required except house number, street address 2 and post code. 

**Tasks**
- [x] Create a 'profiles' application.
- [x] Create a model with fields to include all fields included within the checkoutForm which is sent to Stripe.
- [x] Create forms.py file to include listed fields from model.
- [x]  Create a profile html page which includes the profile custom form on the left side.
- [x] Include all purchases related to the user so they can be displayed on the right side.
- [x]  Create an 'profile" function within views.py to render profile_form and save once fully completed.
