### ISSUE TITLE
USER STORY: View/Edit Profile

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#16]
As a **Site User** I can **view and edit my profile** so that **I can keep my personal information up to date if making an order**

**Acceptance Criteria:**
- Acceptance Criteria 1: profile html page displays logged in user profile to the user.
- Acceptance Criteria 2: profile card to include an update button for site users.
- Acceptance Criteria 3: Users can update all fields of their profile whenever they wish.

**Tasks**
- [x] Create a profile html page which includes a 'Create Profile' button if profile is empty.
- [x] Use the profile function in views.py to render the user's profile.
- [x] Create an update button under user profile which will be linked with 'update profile' button.
