### ISSUE TITLE
USER STORY: Filter and View Specific Categories

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#18]
As a **Site User** I can **filter and view a list of products of a specific category** so that **I search for a specific type of product I am looking for**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must include a dropdown nav bar element which offers all product in categories.
- Acceptance Criteria 2: Each dropdown element must be linked with specific category so user only views products they wish to view.

**Tasks**
- [x] Create a main nav bar to include four dropdown lists. (All Products, Golf Clubs, Accessories and Offers).
- [x] Elements relating to the above must be included within the dropdown list for easy access to the user.
- [x] Must be included within base.html so this feature is available to the user at all times.
- [x] Set up url for each element to match category clicked on.
