### ISSUE TITLE
USER STORY: Sort Products

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#19]
As a **Site User** I can **sort the filtered products to my needs** so that **I can chose whether I want the items in order of price, rating to meet my needs**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must include a sort input/select element within products.html.
- Acceptance Criteria 2: Be able to sort by price, name, quality, brand at least.

**Tasks**
- [ ] Within products.html, create a row to include the sorting select options.
- [ ] Write if statements to match correct sorting method and do both ascending and descending format.
- [ ] Create a JavaScript function which updates the products search depending on the selected sort type automatically.
