### ISSUE TITLE
USER STORY: search for products by name and description

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#20]
As a **Site User** I can **search for products by name and description** so that **I can find a specific product by typing its name into a searchbar**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must include a search bar within header of base.html.
- Acceptance Criteria 2:  Search bar must search word found in product name or description.

**Tasks**
- [x] Include a search within the top header, above the main nav bar. 
- [x] Import a search icon from font awesome
- [x] Use the imported icon as a form to get the data entered within the search bar and use it to find word entered in all products.
