### ISSUE TITLE
USER STORY: Add Product to Basket and View Basket

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#22]
As a **Site User** I can **add individual products to the basket** so that **I can have it ready for checkout but customise if needs to be**

**Acceptance Criteria:**
- Acceptance Criteria 1: product_detail.html must include an 'Add to Basket' button.

**Tasks**
- [x] Create an app called basket and link with main app through settings.py
- [x] Create an 'Add_to_basket' function in views.py and when submitted, get all the product details.
- [x] Add the product to a newly created basket session.
- [x] Create basket.html and display basket product items on the left and order summary to the right.
- [x] Create view_basket function in views.py which renders basket.html.
- [x] Set up url to view_basket function in urls.py
- [x] Add 'Secure Checkout' button to product_detail.html which links with basket.html.
