### ISSUE TITLE
USER STORY: Select Quantity and Size

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#23]
As a **Site User** I can **select the quality and quantity of the product I wish to buy** so that **I can choose how many of a specific item I wish to buy and how good I want it to be**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must include an input field for quantity of items and size selected.
- Acceptance Criteria 2: Must Be features within product_detail.html.

**Tasks**
Using a submit form:
- [x] Create a quantity input with minimum one or more in product_detail.html
- [x] Add boolean field to product model to check if product requires size.
- [x] If size, include a size input field (SX, S, M, L, XL).
- [x] When submitted, product with data is used in add_to_basket function.
