### ISSUE TITLE
USER STORY: Delete Product From Basket

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#25]
As a **Site User** I can **delete a specific product from my shopping basket** so that **I can get rid of a product if I change my mind last minute**

**Acceptance Criteria:**
- Acceptance Criteria 1: Basket.html must include a 'remove item' button which deletes specific product from basket session.

**Tasks**
- [x] In views.py create remove_basket_item function to delete specific product clicked on.
- [x] In urls.py, set up url to link above function.
- [x] Create Remove Button and link it with the url created above.
