### ISSUE TITLE
USER STORY: Enter Billing/Delivery Details

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#26]
As a **Site User** I can **easily enter my personal information during checkout** so that **I can have a speedy process and save my details with ease for the future**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must include a Checkout for which can be saved to user's profile within a click.
- Acceptance Criteria 2: Must match profile model.
- Acceptance Criteria 3: Order Summary and Total cost breakdown must be displayed

**Tasks**
- [x] Create a new app called checkout.
- [x] In models.py, create a new model called 'Order'
- [x] In forms.py, create the CheckoutForm which needs to match profile so it can be saved.
- [x] Include a 'Save' boolean as checkbox.
- [x] In views.py create a function to render checkout.html.
- [x] Create checkout.html which will display checkout form on the left side and order summary.
