### ISSUE TITLE
USER STORY: Secure Payment

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#27]
As a **Site User** I can **feel secure and comfortable typing in payment details during the checkout process** so that **I know the details I entered will not be shared with anyone outside the website and the site adheres to the GDPR Regulation policy**

**Acceptance Criteria:**
- Acceptance Criteria 1: Use Stripe as Payment Service to receive payments for security reasons.
- Acceptance Criteria 2: Include a secure payment section under the checkout form which is linked with stripe upon submission.

**Tasks**
- [ ] In checkout.html, under checkout form.. Create an empty section through which stripe payment will be displayed.
- [ ] Install stripe and link with payment section.
- [ ] Set up webhooks.py and webhook_handler to ensure payment and data transfer is secure.
