### ISSUE TITLE
USER STORY: View Order Details after Payment

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#28]
As a **Site User** I can **view my purchase details after payment** so that **I can review what I have purchased **

**Acceptance Criteria:**
- Acceptance Criteria 1: Page must display all data for order.
- Acceptance Criteria 2:  Button to return to shopping must be included.
- Acceptance Criteria 3: Thank you message at the top of the page. 

**Tasks**
- [x] Create checkout_confirm.html.
- [x] In views.py, create checkout_confirm function which return the order details as context.
- [x] In urls.py, set up a url to call the above function linked with checkout_confirm.html.
- [x] If payment processed, display order details in the middle of the page.
- [x] Create a button which is linked with 'products' url to return the user to all products.
