### ISSUE TITLE
USER STORY: Send Email Confirmation

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#29]
As a **Site User** I can **receive and view an email summary after checkout** so that **I can keep a backup of my recent purchase incase I need it in the future**

**Acceptance Criteria:**
- Acceptance Criteria 1: Email confirmation must be sent with order details if payment is successful. 

**Tasks**
- [x] In checkout/templates, create confirmation_email_subject.txt and include email subject.
- [x] In checkout/templates, create confirmation_email_body.txt and include main structure of email.
- [x] In settings.py, set up django's backend email field.
- [x] Add 'send email' function if payment is successful.
