### ISSUE TITLE
USER STORY: View all products

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#3]
As a **Site User** I can **easily access and view a list of products** so that **I can view what the site has to offer in one place**

**Acceptance Criteria:**
- Acceptance Criteria 1: Have one webpage where users can surf through all of the products offered by Golf Mania.
- Acceptance Criteria 2:  Product pictures must be big and vital information to be displayed to get the user's attention.

**Tasks**
- [x] Create a Products app and link with the main application.
- [x] Create a custom product's app, add it to admin.py and add products using the admin panel.
- [x] Create a view function which collects all products and displays on a custom html page as context.
- [x] Create a custom products.html page and display products in rows of 4 on larger screens.
