### ISSUE TITLE
USER STORY: Access the Admin Panel

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#31]
As a **Site Admin** I can **access the admin panel** so that **I can change anything regarding the online shops database**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must have access to all products, profiles, users, reviews, orders etc.
- Acceptance Criteria 2: Must have a link included in the main header if superuser is logged in.

**Tasks**
- [x] Set up url to admin panel within the main apps urls.py.
- [x] Within base.html, include a dropdown element for 'Admin Panel' and link it with url created above.
- [x] Use if statement to test if superuser is requested this for secure reasons.
