### ISSUE TITLE
USER STORY: Add and View New Product

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#32]
As a **Site Admin** I can **add a new product** so that **I do not need to access the admin panel to do so and see an instant update**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must be easily accessible 
- Acceptance Criteria 2: Must be done efficiently.

**Tasks**
- [x] In products app, create add_product.html with a submit form for a new product.
- [x] In forms.py create productForm.
- [x] In views.py, create add_product function.
- [x] In urls.py, link above function which will display add_product.html with productForm.
- [x] In base.html, in main header, create dropdown element as 'Add Product' and link above url with it.
- [x] It should render the product_detail page of new product.
