### ISSUE TITLE
USER STORY: Edit Product

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#33]
As a **Site Admin** I can **update any product** so that **I can make changes to any product at any time**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must be a feature included in all products.
- Acceptance Criteria 2: Changes can be updated and displayed instantly.

**Tasks**
- [x] In views.py, create new function update_product.
- [x] Create update_product.html which will be rendered in the above function.
- [x] In urls.py, set up link to call update_product function.
- [x] Within products.html and product_detail.html, include an 'Update' button and link with url created above.
