### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#34]
As a **Site Admin** I can **delete any product** so that **I can update my website as needed**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must be a feature included in all products.
- Acceptance Criteria 2: Deleted products are removed instantly.
- Acceptance Criteria 3: Superuser is asked again if they wish to delete product in case of a mistake.

**Tasks**
- [x] In views.py, create new function delete_product.
- [x] Create delete_product.html which will be rendered in the above function. (To include delete functionality and cancel button)
- [x] In urls.py, set up link to call delete_product function.
- [x] Within products.html and product_detail.html, include an 'Delete' button and link with url created above.
