### ISSUE TITLE
USER STORY: Social Account Log In

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#35]
As a **Site User** I can **use my social media account** so that **I can register without needing to fill out the registration form**

**Acceptance Criteria:**
- Acceptance Criteria 1: Facebook must be a social site through which customers can register/log in.

**Tasks**
- [ ] Log into Facebook's - developer settings and import keys/api.
- [ ] Migrate the database to allow social accounts.
- [ ] In settings.py, update configurations and context processor.
- [ ] In settings.py, add Authentication backends.
- [ ] In urls.py, add social-auth-app-django urls.
- [ ] In settings.py, add default login and logout variables.
