### ISSUE TITLE
USER STORY: Click and review product in Detail

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#4]
As a **Site User** I can **click and view each product in detail** so that **I can get to know each product in more detail and help my decision-making process**.

**Acceptance Criteria:**
- Acceptance Criteria 1: Product picture must be at least 400px.
- Acceptance Criteria 2:  All details regarding the unique product must be displayed.
- Acceptance Criteria 3: Must include functions such as adding to the basket, back to products, change quantity.

**Tasks**
- [x] Within the products app, create a custom product_detail.html page which displays each product in detail.
- [x] To include product image (400px) on the left and product data on the right.
- [x] Must have a link to go back to products, add product to the basket and be able to change quantity.
