### ISSUE TITLE
USER STORY: View Deals and/or Sales 

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#7]
As a **Site Users** I can **easily find the available deals/sales** so that **I can easily catch the best deals available to me**

**Acceptance Criteria:**
- Acceptance Criteria 1: Include sections throughout the app where offers are displayed to the user.
- Acceptance Criteria 2: Must include different types of offers so that the user is not looking at the same products offered everywhere.

**Tasks**
- [ ] Create a section in index.html to include products of one type as a row that user's can click on and be taken to the unique product.
- [ ] Create another section in product_details.html where other offers are displayed. (Below product_details).
- [ ] Create a final section to offer highlighted products to the user after the purchasing experience. (checkout_confirm.html)
