### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/GolfMania#8]
As a **Site User** I can **register an account** so that **I can save my personal details for my next purchase**

**Acceptance Criteria:**
- Acceptance Criteria 1: Use Django Allauth to allow users to create an account using an email and a password.
- Acceptance Criteria 2: Accounts must also have usernames.

**Tasks**
- [x] Install AllAuth and customise signup.html.
- [x] Make username and email fields required.
- [x] Add AllAuth template links to main apps urls.py and set email and user required in settings.py.
- [x] Include link to signup.html via header.
